### ISSUE TITLE
Display lack at game ending

### ISSUE THREAD

**Issue by Zoidrums** [ireade/tictactoe#3]
Hi,
when a game is won (by player or computer), the last mark (X or O) isn't display. I've tried to put a "sleep" simulator for the game to show the last mark but it doesn't work. I don't know how to see the winner mark.

Zoidrums

**Comment by ireade** [comment]
Hi @Zoidrums ! Thanks for the info. Unfortunately I am no longer maintaining this project. If you like you are welcome fork it and make the changes yourself.
